### ISSUE TITLE
TypeError: Cannot read property 'currentPage' of undefined

### ISSUE THREAD

**Issue by alsoicode** [bradmartin/nativescript-snackbar#32]
I'm brand-new to NativeScript, so please bear with me. I created a new app using the latest NativeScript, and just as a test, tried adding a SnackBar message to a component:

```
import { Component } from "@angular/core";
import { SnackBar } from 'nativescript-snackbar';

@Component({
  selector: "ns-app",
  templateUrl: "app.component.html",
})
export class AppComponent {
  openSnackbar(): void {
    const snackBar = new SnackBar();
    snackBar.simple('It works!');
  }
}
```

The stack trace I received back was:

JS: TypeError: Cannot read property 'currentPage' of undefined
JS:     at file:///data/data/org.nativescript.TeeocaAttendance/files/app/tns_modules/nativescript-snackbar/snackbar.js:28:96
JS:     at new ZoneAwarePromise (file:///data/data/org.nativescript.TeeocaAttendance/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:777:29)
JS:     at SnackBar.simple (file:///data/data/org.nativescript.TeeocaAttendance/files/app/tns_modules/nativescript-snackbar/snackbar.js:22:16)
JS:     at AppComponent.openSnackbar (file:///data/data/org.nativescript.TeeocaAttendance/files/app/app.component.js:22:18)
JS:     at Object.eval [as handleEvent] (ng:///AppModule/AppComponent.ngfactory.js:24:27)
JS:     at handleEvent (file:///data/data/org.nativescript.TeeocaAttendance/files/app/tns_modules/@angular/core/bundles/core.umd.js:13627:155)
JS:     at callWithDebugContext (file:///data/data/org.nativescript.TeeocaAttendance/files/app/tns_modules/@angular/core/bundles/core.umd.js:15136:42)
JS:     at Object.debugHandleEvent [as handleEvent] (file:///data/data/org.nativescript.TeeocaAttendance/files/app/tns_modules/@angular/core/bundles/core.umd.js:14723:12)
JS:     at dispatchEvent (file:///data/data/org.nativescript.TeeocaAttendance/files/app/tns_modules/@angular/core/bundles/core.umd.js:10042:25)
JS:     at file:///data/data/org.nativescript.TeeocaAttendance/files/app/tns_modules/@angular/core/bundles/core.umd.js:10667:38
JS:     at file:///data/data/org.nativescript.TeeocaAttendance/files/app/tns_modules/nativescript-angular/renderer.js:186:26
JS:     at ZoneDelegate.invoke (file:///data/data/org.nativescript.TeeocaAttendance/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:365:26)
JS:     at Object.onInvoke (file:///data/data/org.nativescript.TeeocaAttendance/files/app/tns_modules/@angular/core/bundles/core.umd.js:4798:33)
JS:     at ZoneDelegate.invoke (file:///data/data/org.nativescript.TeeocaAttendance/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:364:32)
JS:     at Zone.run (file:///data/data/org.nativescript.TeeocaAttendance/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:125:43)
JS: ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'currentPage' of undefined
JS: TypeError: Cannot read property 'currentPage' of undefined
JS:     at file:///data/data/org.nativescript.TeeocaAttendance/files/app/tns_modules/nativescript-snackbar/snackbar.js:28:96
JS:     at new ZoneAwarePromise (file:///data/data/org.nativescript.TeeocaAttendance/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:777:29)
JS:     at SnackBar.simple (file:///data/data/org.nativescript.TeeocaAttendance/files/app/tns_modules/nativescript-snackbar/snackbar.js:22:16)
JS:     at AppComponent.openSnackbar (file:///data/data/org.nativescript.TeeocaAttendance/files/app/app.component.js:22:18)
JS:     at Object.eval [as handleEvent] (ng:///AppModule/AppComponent.ngfactory.js:24:27)
JS:     at handleEvent (file:///data/data/org.nativescript.TeeocaAttendance/files/app/tns_modules/@angular/core/bundles/core.umd.js:13627:155)
JS:     at callWithDebugContext (file:///data/data/org.nativescript.TeeocaAttendance/files/app/tns_modules/@angular/core/bundles/core.umd.js:15136:42)
JS:     at Object.debugHandleEvent [as handleEvent] (file:///data/data/org.nativescript.TeeocaAttendance/files/app/tns_modules/@angular/core/bundles/core.umd.js:14723:12)
JS:     at dispatchEvent (file:///data/data/org.nativescript.TeeocaAttendance/files/app/tns_modules/@angular/core/bundles/core.umd.js:10042:25)
JS:     at file:///data/data/org.nativescript.TeeocaAttendance/files/app/tns_modules/@angular/core/bundles/core.umd.js:10667:38
JS:     at file:///data/data/org.nativescript.TeeocaAttendance/files/app/tns_modules/nativescript-angular/renderer.js:186:26
JS:     at ZoneDelegate.invoke (file:///data/data/org.nativescript.TeeocaAttendance/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:365:26)
JS:     at Object.onInvoke (file:///data/data/org.nativescript.TeeocaAttendance/files/app/tns_modules/@angular/core/bundles/core.umd.js:4798:33)
JS:     at ZoneDelegate.invoke (file:///data/data/org.nativescript.TeeocaAttendance/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:364:32)
JS:     at Zone.run (file:///data/data/org.nativescript.TeeocaAttendance/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:125:43)

I'm using nativescript-angular 5.3.0 and nativescript-snackbar 3.0.0 on Windows 10. I tried removing the android platform files for the project and then adding the platform back, re-building, and re-installing my Node modules, but I still get the same error.

**Comment by alsoicode** [comment]
Sorry for wasting your time. I realized that my default template didn't have a `<page-router-outlet></page-router-outlet>` I added that and moved the Snackbar call to a subsequent component and it works as expected.
