### ISSUE TITLE
Not working for android NS 1.6.1

### ISSUE THREAD

**Issue by Daxito** [bradmartin/nativescript-snackbar#6]
I keep getting this error when using on android, ios is ok but android is not, I am using {N} 1.6.1 and maybe something broke it with this new version, any idea? 

java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException:  Error calling module function
TypeError: Cannot read property 'widget' of undefined File: "<unknown>, line: 1, column: 265
StackTrace:  Frame: function:'', file:'/data/data/com.yyy.yy/files/app/tns_modules/nativescript-snackbar/index.js', line: 144, column: 49 Frame: function:'require', file:'', line: 1, column: 266 Frame: function:'', file:'/data/data/com.yyy.yy/files/app/service/connection-monitor.js', line: 4, column: 16 Frame: function:'require', file:'', line: 1, column: 266 Frame: function:'', file:'/data/data/com.yyy.yy/files/app/app.js', line: 4, column: 25 
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5013) at android.app.ActivityThread.access$1600(ActivityThread.java:172) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1482) at android.os.Handler.dispatchMessage(Handler.java:102) at android.os.Looper.loop(Looper.java:145) at android.app.ActivityThread.main(ActivityThread.java:5835) at java.lang.reflect.Method.invoke(Native Method) at java.lang.reflect.Method.invoke(Method.java:372) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194) Caused by: com.tns.NativeScriptException:  Error calling module function
TypeError: Cannot read property 'widget' of undefined File: "<unknown>, line: 1, column: 265
StackTrace:  Frame: function:'', file:'/data/data/com.yyy.yy/files/app/tns_modules/nativescript-snackbar/index.js', line: 144, column: 49 Frame: function:'require', file:'', line: 1, column: 266 Frame: function:'', file:'/data/data/com.yyy.yy/files/app/service/connection-monitor.js', line: 4, column: 16 Frame: function:'require', file:'', line: 1, column: 266 Frame: function:'', file:'/data/data/com.yyy.yy/files/app/app.js', line: 4, column: 25 
at com.tns.Platform.runModule(Native Method) at com.tns.Platform.runModule(Platform.java:189) at com.tns.Platform.run(Platform.java:181) at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:1035) at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1020) at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5010) ... 9 more

**Comment by bradmartin** [comment]
I haven't tested it but that error indicates your support library isn't
pulling in from the build. Try removing the platform and add back in, watch
the console and make sure the android support library is in the build. Also
make sure you have the support library updated to latest (23.1.1)

**Comment by Daxito** [comment]
Removing and adding the platform fixed the issue, I will keep that in mind every time I add a plugin or weird stuff happens.
thank you!

**Comment by bradmartin** [comment]
Glad to hear :)
